using System;

namespace SourceGit.Models
{
    /// <summary>
    ///     Guesses the encoding used by the content of a patch generated by `git diff`.
    ///
    ///     `Feed` is expected to be called once per body line of the patch, with the leading type
    ///     marker removed. Working line by line is safe because '\n' is never part of a multi-byte
    ///     character in any of the candidate encodings.
    /// </summary>
    public class EncodingDetector
    {
        public void Feed(ReadOnlySpan<byte> content)
        {
            if (content.IndexOfAnyExceptInRange((byte)0x00, (byte)0x7F) < 0)
                return;

            _hasNonASCII = true;

            if (_maybeUTF8)
                _maybeUTF8 = TestUTF8(content);

            foreach (var candidate in _candidates)
                candidate.Feed(content);
        }

        public TextEncoding GetResult()
        {
            // Pure ASCII or a well-formed UTF-8 sequence: UTF-8 decodes both correctly. Text written
            // with a legacy code page rarely forms a valid UTF-8 sequence, so this test alone already
            // sorts out most of the files.
            if (!_hasNonASCII || _maybeUTF8)
                return TextEncoding.UTF8;

            Candidate best = null;
            foreach (var candidate in _candidates)
            {
                if (!candidate.IsValid || candidate.Confidence < MIN_CONFIDENCE)
                    continue;

                if (best == null || candidate.Score > best.Score)
                    best = candidate;
            }

            // Nothing matched, so the content is either written with a single byte encoding or is not
            // really text. A single byte encoding decodes anything, which at least keeps the lines
            // readable.
            return best?.Encoding ?? TextEncoding.Windows1252;
        }

        private enum CodePageKind
        {
            GB18030,
            Big5,
            ShiftJIS,
            EUCKR,
        }

        private class Candidate(TextEncoding encoding, CodePageKind kind)
        {
            public TextEncoding Encoding { get; } = encoding;

            /// <summary>
            ///     Turns false once a byte sequence this code page can not represent is found.
            /// </summary>
            public bool IsValid { get; private set; } = true;

            /// <summary>
            ///     How many multi-byte characters were read.
            /// </summary>
            public int Total { get; private set; } = 0;

            /// <summary>
            ///     The ratio of multi-byte characters made of two non-ASCII bytes that also land in the
            ///     block real text written with this code page mostly uses. A code page that merely
            ///     accepts the bytes loses against one that also finds meaningful characters in them.
            /// </summary>
            public double Confidence => Total == 0 ? 0 : _common / (double)Total;

            public double Score => Confidence + (Encoding == SYSTEM_DEFAULT ? SYSTEM_DEFAULT_BONUS : 0);

            public void Feed(ReadOnlySpan<byte> content)
            {
                if (!IsValid)
                    return;

                for (int i = 0; i < content.Length; i++)
                {
                    if (content[i] < 0x80)
                        continue;

                    if (!TryRead(content, i, out var length, out var isCommon))
                    {
                        IsValid = false;
                        return;
                    }

                    if (length > 1)
                    {
                        Total++;
                        if (isCommon)
                            _common++;
                    }

                    i += length - 1;
                }
            }

            private bool TryRead(ReadOnlySpan<byte> content, int start, out int length, out bool isCommon)
            {
                length = 1;
                isCommon = false;

                var lead = content[start];

                // Half-width katakana is the only single byte character above the ASCII range.
                if (kind == CodePageKind.ShiftJIS && lead is >= 0xA1 and <= 0xDF)
                    return true;

                if (lead is < 0x81 or 0xFF)
                    return false;

                if (start + 1 >= content.Length)
                    return false;

                var trail = content[start + 1];
                length = 2;

                switch (kind)
                {
                    case CodePageKind.GB18030:
                        // A digit as the second byte introduces the four bytes form, which holds the
                        // code points GBK does not have. No other candidate accepts those bytes as a
                        // character, so finding one is a strong hint on its own.
                        if (trail is >= 0x30 and <= 0x39)
                        {
                            if (start + 3 >= content.Length)
                                return false;
                            if (content[start + 2] is < 0x81 or > 0xFE || content[start + 3] is < 0x30 or > 0x39)
                                return false;

                            length = 4;
                            isCommon = true;
                            return true;
                        }

                        if (trail is < 0x40 or 0x7F or 0xFF)
                            return false;

                        // The GB2312 block, which covers the symbols and simplified Chinese used in
                        // practice.
                        isCommon = lead <= 0xF7 && trail >= 0xA1;
                        return true;

                    case CodePageKind.Big5:
                        if (trail is not (>= 0x40 and <= 0x7E) and not (>= 0xA1 and <= 0xFE))
                            return false;

                        // Symbols and both levels of traditional Chinese. Only the trail bytes above
                        // the ASCII range count, so that a western text made of isolated high bytes
                        // does not pass as traditional Chinese.
                        isCommon = lead <= 0xF9 && trail >= 0xA1;
                        return true;

                    case CodePageKind.ShiftJIS:
                        if (lead is not (<= 0x9F) and not (>= 0xE0 and <= 0xFC))
                            return false;
                        if (trail is < 0x40 or 0x7F or > 0xFC)
                            return false;

                        // Kana and the first level of kanji.
                        isCommon = lead <= 0xEA && trail >= 0x80;
                        return true;

                    case CodePageKind.EUCKR:
                        if (trail is not (>= 0x41 and <= 0x5A) and not (>= 0x61 and <= 0x7A) and not (>= 0x81 and <= 0xFE))
                            return false;

                        // The symbols, hangul syllables and hanja of KS X 1001.
                        isCommon = trail >= 0xA1;
                        return true;

                    default:
                        return false;
                }
            }

            private int _common = 0;
        }

        /// <summary>
        ///     Strictly validates a UTF-8 byte sequence. Overlong forms, surrogates and code points
        ///     above the Unicode range are all rejected, since accepting them would let text written
        ///     with a legacy code page pass as UTF-8.
        /// </summary>
        private static bool TestUTF8(ReadOnlySpan<byte> content)
        {
            for (int i = 0; i < content.Length; i++)
            {
                var lead = content[i];
                if (lead < 0x80)
                    continue;

                int trails, code, min;
                if (lead is >= 0xC2 and <= 0xDF)
                    (trails, code, min) = (1, lead & 0x1F, 0x80);
                else if (lead is >= 0xE0 and <= 0xEF)
                    (trails, code, min) = (2, lead & 0x0F, 0x800);
                else if (lead is >= 0xF0 and <= 0xF4)
                    (trails, code, min) = (3, lead & 0x07, 0x10000);
                else
                    return false; // A trailing byte out of place, or an overlong two bytes form.

                if (i + trails >= content.Length)
                    return false;

                for (int j = 1; j <= trails; j++)
                {
                    var trail = content[i + j];
                    if (trail is < 0x80 or > 0xBF)
                        return false;

                    code = (code << 6) | (trail & 0x3F);
                }

                if (code < min || code > 0x10FFFF || code is >= 0xD800 and <= 0xDFFF)
                    return false;

                i += trails;
            }

            return true;
        }

        // A candidate that accepts the bytes but finds few meaningful characters in them is most
        // likely wrong: the content is then probably written with a single byte encoding.
        private const double MIN_CONFIDENCE = 0.3;

        // Nudges the code page of the running system ahead of the equally confident ones. Code pages
        // that share their byte ranges can not really be told apart without the character frequencies
        // this detector does not have: simplified Chinese, traditional Chinese and Korean all live in
        // the same two byte ranges. Falling back to the code page of the system is what makes the
        // common case right, and the previewer lets the encoding be picked by hand for the rest.
        private const double SYSTEM_DEFAULT_BONUS = 0.05;

        // GBK is a subset of GB18030, so a system running the former is served by the latter.
        private static readonly TextEncoding SYSTEM_DEFAULT =
            TextEncoding.SystemDefault == TextEncoding.GBK ? TextEncoding.GB18030 : TextEncoding.SystemDefault;

        // Ordered from the most to the least likely, which decides ties between equally confident
        // candidates.
        private readonly Candidate[] _candidates =
        [
            new Candidate(TextEncoding.GB18030, CodePageKind.GB18030),
            new Candidate(TextEncoding.Big5, CodePageKind.Big5),
            new Candidate(TextEncoding.ShiftJIS, CodePageKind.ShiftJIS),
            new Candidate(TextEncoding.EUCKR, CodePageKind.EUCKR),
        ];

        private bool _hasNonASCII = false;
        private bool _maybeUTF8 = true;
    }
}
